//#include<iostream>
//
//using namespace std;
//
//int func(int i) //THROWS EXCEPTIONS!
//{
//	//EXCEPTION ONE!!!!!!
//	if (i > 10)
//	{
//		throw("LARGER THAN 10 EXCEPTION!!!!");
//	}
//	
//	return i;
//}
//
//int main()
//{
//	//TRY - CATCH BLOCK
//	try
//	{
//		cout << func(12) << endl;
//	}
//	catch (char *c)
//	{
//		cout << c << endl;
//	}
//
//	system("PAUSE");
//
//	return 0;
//}
